#######################
#### グローバル設定 ####
#######################
# 拡張モジュールの読み込みや、ログファイルのグループ/オーナ指定など、
# rsyslogの動作全編に関する設定をする。

#### MODULES ####
module(load="imtcp")
input(type="imtcp" port="514")




#####################
#### テンプレート ####
#####################
# ログファイルに出力されるログメッセージのフォーマットを作成する。



#######################################
#### ルール：ログメッセージ出力ルール ####
#######################################
# ログメッセージを指定し、保存方法や出力方法を設定する。
*.* /var/log/remote/syslog.log